///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This file is auto-generated by api_generator. DO NOT EDIT!
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#pragma once

#ifdef _cplusplus
extern "C" {
#endif

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

struct RVServicePrivData;

struct RVIo;
struct RVLog;
struct RVMetadata;
struct RVSettings;

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

typedef struct RVService {
    struct RVServicePrivData* private_data;
    const struct RVIo* (*get_io)(struct RVServicePrivData* private_data, int api_version);
    const struct RVLog* (*get_log)(struct RVServicePrivData* private_data, int api_version);
    const struct RVMetadata* (*get_metadata)(struct RVServicePrivData* private_data, int api_version);
    const struct RVSettings* (*get_settings)(struct RVServicePrivData* private_data, int api_version);
} RVService;

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#define RVService_get_io(api, version) api->get_io(api->private_data, version)
#define RVService_get_log(api, version) api->get_log(api->private_data, version)
#define RVService_get_metadata(api, version) api->get_metadata(api->private_data, version)
#define RVService_get_settings(api, version) api->get_settings(api->private_data, version)

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#ifdef _cplusplus
}
#endif
