// @generated by api_gen — DO NOT EDIT. Regenerate with scripts/gen_bindings.sh.

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum RVAudioStreamFormat {
    RVAudioStreamFormat_U8 = 1,
    RVAudioStreamFormat_S16 = 2,
    RVAudioStreamFormat_S24 = 3,
    RVAudioStreamFormat_S32 = 4,
    RVAudioStreamFormat_F32 = 5,
} RVAudioStreamFormat;

typedef struct RVAudioFormat {
    RVAudioStreamFormat audio_format;
    uint32_t channel_count;
    uint32_t sample_rate;
} RVAudioFormat;


#ifdef __cplusplus
}
#endif
