// @generated by api_gen — DO NOT EDIT. Regenerate with scripts/gen_bindings.sh.

#pragma once

#include <stdint.h>
#include "audio_format.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct RVService RVService;

typedef struct RVWriteInfo {
    uint32_t sample_rate;
    uint16_t sample_count;
    uint8_t channel_count;
    uint8_t output_format;
} RVWriteInfo;

typedef struct RVPlaybackCallback {
    void* user_data;
    uint32_t (*callback)(void* user_data, void* data, RVAudioFormat format, uint32_t frames);
} RVPlaybackCallback;

typedef struct RVOutputTargets {
    void* names;
    uint64_t names_size;
} RVOutputTargets;

typedef struct RVOutputPlugin {
    uint64_t api_version;
    const char* name;
    const char* version;
    const char* library_version;
    void* (*create)(const RVService* services);
    int32_t (*destroy)(void* user_data);
    RVOutputTargets (*output_targets_info)(void* user_data);
    void (*start)(void* user_data, RVPlaybackCallback* callback);
    void (*stop)(void* user_data);
    void (*static_init)(const RVService* services);
} RVOutputPlugin;


#ifdef __cplusplus
}
#endif
