// @generated by api_gen — DO NOT EDIT. Regenerate with scripts/gen_bindings.sh.

#pragma once

#include <stdbool.h>
#include <stdint.h>
#include "audio_format.h"

#define RV_PLAYBACK_PLUGIN_API_VERSION 2

#ifdef __cplusplus
extern "C" {
#endif

// Result of probing a candidate file to decide whether this plugin can play it.
typedef enum RVProbeResult {
    // The plugin recognizes the data and can play it.
    RVProbeResult_Supported = 0,
    // The plugin is certain it cannot play the data.
    RVProbeResult_Unsupported = 1,
    // The plugin cannot tell from the data alone (host may try opening it).
    RVProbeResult_Unsure = 2,
} RVProbeResult;

// Status of a single `read_data` call.
typedef enum RVReadStatus {
    // No audio produced yet; the plugin is still preparing (host should retry).
    RVReadStatus_DecodingRequest = 0,
    // Audio frames were produced successfully.
    RVReadStatus_Ok = 1,
    // The song reached its end; no more audio will follow.
    RVReadStatus_Finished = 2,
    // A decoding error occurred; playback should stop.
    RVReadStatus_Error = 3,
} RVReadStatus;

// Whether a settings change can be applied live or needs a restart of the song.
typedef enum RVSettingsUpdate {
    // New settings took effect immediately.
    RVSettingsUpdate_Default = 0,
    // The song must be reopened for the new settings to apply.
    RVSettingsUpdate_RequireRestart = 1,
} RVSettingsUpdate;

// What a plugin can show on the visualization surface. A plugin advertises these
// in `VizInfo.caps`; the host enables only the features the plugin reports.
typedef enum RVVizCaps {
    // Provides tracker pattern cells (`tracker_cells` and the column/channel queries).
    RVVizCaps_PatternCells = 1,
    // Provides per-channel oscilloscope waveforms (`scope_samples`).
    RVVizCaps_Scope = 2,
    // Provides per-channel VU levels (`vu_levels`).
    RVVizCaps_Vu = 4,
    // The whole song is available as a window from the moment it opens.
    RVVizCaps_WholeSongKnown = 8,
    // Cells ahead of the current position can be previewed before they play.
    RVVizCaps_SeekablePreview = 16,
    // Future rows are known and stable (not synthesized as playback advances).
    RVVizCaps_FutureKnown = 32,
} RVVizCaps;

// How pattern channels advance through rows.
typedef enum RVScrollMode {
    // All channels share one row position (e.g. MOD/XM).
    RVScrollMode_Synchronized = 0,
    // Each channel scrolls at its own row position (e.g. TFMX).
    RVScrollMode_PerChannel = 1,
} RVScrollMode;

// What a tracker pattern column holds, used by the host for coloring and layout.
typedef enum RVColumnKind {
    // Note column (pitch / note-off).
    RVColumnKind_Note = 0,
    // Instrument or sample number.
    RVColumnKind_Instrument = 1,
    // Volume column.
    RVColumnKind_Volume = 2,
    // Effect command.
    RVColumnKind_Effect = 3,
    // Effect parameter.
    RVColumnKind_Param = 4,
    // Plugin-specific column with no standard meaning.
    RVColumnKind_Custom = 5,
} RVColumnKind;

typedef struct RVService RVService;

// Format and outcome of a block of decoded audio.
typedef struct RVReadInfo {
    // Sample format, channel count, and sample rate of the produced frames.
    RVAudioFormat format;
    // Number of audio frames produced.
    uint32_t frame_count;
    // Outcome of the read.
    RVReadStatus status;
} RVReadInfo;

// Destination buffer and resulting info for a `read_data` call.
typedef struct RVReadData {
    // Caller-owned output buffer the plugin writes interleaved frames into.
    void* channels_output;
    // Capacity of `channels_output` in bytes.
    uint32_t channels_output_max_bytes_size;
    // Filled in by the plugin to describe what it produced.
    RVReadInfo info;
} RVReadData;

// One-time description of a plugin's visualization surface, queried with `viz_info`
// after the song opens. Counts here size the buffers the host passes to the
// column, channel, and cell queries.
typedef struct RVVizInfo {
    // Bitset of `VizCaps` the plugin supports.
    uint32_t caps;
    // How pattern channels scroll.
    RVScrollMode scroll_mode;
    // Number of channels in the pattern grid.
    uint32_t pattern_channel_count;
    // Number of channels with an oscilloscope.
    uint32_t scope_channel_count;
    // Number of columns per pattern channel.
    uint32_t column_count;
} RVVizInfo;

// Description of one tracker pattern column, queried once with `tracker_columns`.
typedef struct RVColumnDesc {
    // Short display label (UTF-8, NUL-padded).
    uint8_t label[16];
    // Rendered text width of this column in characters (at most 16).
    uint8_t char_width;
    // What the column holds.
    RVColumnKind kind;
} RVColumnDesc;

// Description of one channel, queried once with `tracker_channels` or `scope_channels`.
typedef struct RVChannelDesc {
    // Short channel name (UTF-8, NUL-padded).
    uint8_t name[24];
    // Oscilloscope width: 1 for mono, 2 for interleaved stereo.
    uint8_t scope_width;
} RVChannelDesc;

// Live musical position of the playhead, queried per frame with `tracker_position`.
typedef struct RVTrackerPosition {
    // Index into the order list.
    uint32_t order;
    // Pattern currently playing.
    uint32_t pattern;
    // Current row within the pattern.
    uint32_t row;
    // Lowest row index currently valid for `tracker_cells`.
    uint32_t window_lo;
    // One past the highest valid row index for `tracker_cells`.
    uint32_t window_hi;
} RVTrackerPosition;

// One tracker pattern cell: the plugin's raw value plus its own rendered text.
typedef struct RVPatternCell {
    // Format-specific raw value; the host uses it for coloring.
    uint32_t raw;
    // Fixed-width rendered text the host lays out directly (UTF-8, NUL-padded).
    uint8_t text[16];
} RVPatternCell;

// The interface a host loads to play one or more retro music formats and, optionally,
// visualize what is playing. The host fills `user_data` from `create` and passes it
// back to every per-instance call.
typedef struct RVPlaybackPlugin {
    // ABI version the plugin was built against; must equal RV_PLAYBACK_PLUGIN_API_VERSION.
    uint64_t api_version;
    // Human-readable plugin name.
    const char* name;
    // Plugin version string.
    const char* version;
    // Version of the underlying decoder library, if any.
    const char* library_version;
    // Inspect file data (and optionally its name) to report whether this plugin can play it.
    RVProbeResult (*probe_can_play)(uint8_t* data, uint64_t data_size, const char* filename, uint64_t total_size);
    // Comma-separated list of file extensions this plugin handles.
    const char* (*supported_extensions)(void);
    // Create a plugin instance, returning its `user_data` handle.
    void* (*create)(const RVService* services);
    // Destroy an instance created by `create`.
    int32_t (*destroy)(void* user_data);
    // Deliver a host event to the instance.
    void (*event)(void* user_data, uint8_t* data, uint64_t data_size);
    // Open a song (optionally a specific subsong) for playback.
    int32_t (*open)(void* user_data, const char* url, uint32_t subsong, const RVService* services);
    // Close the song opened with `open`, leaving the instance reusable.
    void (*close)(void* user_data);
    // Decode the next block of audio into the caller's buffer.
    RVReadInfo (*read_data)(void* user_data, RVReadData dest);
    // Seek to a position in milliseconds; returns the position actually reached.
    int64_t (*seek)(void* user_data, int64_t ms);
    // Read metadata for a song without opening it for playback.
    int32_t (*metadata)(const char* url, const RVService* services);
    // One-time process-wide setup, called once before any instance is created.
    void (*static_init)(const RVService* services);
    // React to a settings change for an instance.
    RVSettingsUpdate (*settings_updated)(void* user_data, const RVService* services);
    // One-time process-wide teardown, called once after all instances are destroyed.
    void (*static_destroy)(void);
    // Describe the visualization surface once after `open`; returns false if the
    // instance has nothing to visualize. A null pointer means no visualization at all.
    bool (*viz_info)(void* user_data, RVVizInfo* out);
    // Fill up to `cap` column descriptions; returns the number written.
    uint32_t (*tracker_columns)(void* user_data, RVColumnDesc* out, uint32_t cap);
    // Fill up to `cap` pattern-channel descriptions; returns the number written.
    uint32_t (*tracker_channels)(void* user_data, RVChannelDesc* out, uint32_t cap);
    // Fill up to `cap` scope-channel descriptions; returns the number written.
    uint32_t (*scope_channels)(void* user_data, RVChannelDesc* out, uint32_t cap);
    // Report the live playhead position; returns false if unavailable this frame.
    bool (*tracker_position)(void* user_data, RVTrackerPosition* out);
    // Fill up to `cap` per-channel row counts (for per-channel scrolling); returns the number written.
    uint32_t (*tracker_channel_rows)(void* user_data, uint32_t* out, uint32_t cap);
    // Fill cells for `channel` over rows [row_lo, row_hi) into `out` (one PatternCell
    // per column per row); returns the number of cells written.
    uint32_t (*tracker_cells)(void* user_data, int32_t channel, uint32_t row_lo, uint32_t row_hi, RVPatternCell* out, uint32_t cap);
    // Turn oscilloscope capture on or off; off by default to avoid its cost.
    void (*scope_enable)(void* user_data, bool on);
    // Copy up to `cap` most-recent scope samples for `channel` as float [-1, 1] at
    // playback rate; returns the number written.
    uint32_t (*scope_samples)(void* user_data, int32_t channel, float* out, uint32_t cap);
    // Fill up to `cap` per-channel VU levels; returns the number written.
    uint32_t (*vu_levels)(void* user_data, float* out, uint32_t cap);
} RVPlaybackPlugin;


#ifdef __cplusplus
}
#endif
