// @generated by api_gen — DO NOT EDIT. Regenerate with scripts/gen_bindings.sh.

#pragma once

#include <stdbool.h>
#include <stdint.h>
#include "audio_format.h"

#define RV_PLAYBACK_PLUGIN_API_VERSION 2

#ifdef __cplusplus
extern "C" {
#endif

typedef enum RVProbeResult {
    RVProbeResult_Supported = 0,
    RVProbeResult_Unsupported = 1,
    RVProbeResult_Unsure = 2,
} RVProbeResult;

typedef enum RVReadStatus {
    RVReadStatus_DecodingRequest = 0,
    RVReadStatus_Ok = 1,
    RVReadStatus_Finished = 2,
    RVReadStatus_Error = 3,
} RVReadStatus;

typedef enum RVSettingsUpdate {
    RVSettingsUpdate_Default = 0,
    RVSettingsUpdate_RequireRestart = 1,
} RVSettingsUpdate;

typedef enum RVVizCaps {
    RVVizCaps_PatternCells = 1,
    RVVizCaps_Scope = 2,
    RVVizCaps_Vu = 4,
    RVVizCaps_WholeSongKnown = 8,
    RVVizCaps_SeekablePreview = 16,
    RVVizCaps_FutureKnown = 32,
} RVVizCaps;

typedef enum RVScrollMode {
    RVScrollMode_Synchronized = 0,
    RVScrollMode_PerChannel = 1,
} RVScrollMode;

typedef enum RVColumnKind {
    RVColumnKind_Note = 0,
    RVColumnKind_Instrument = 1,
    RVColumnKind_Volume = 2,
    RVColumnKind_Effect = 3,
    RVColumnKind_Param = 4,
    RVColumnKind_Custom = 5,
} RVColumnKind;

typedef struct RVService RVService;

typedef struct RVReadInfo {
    RVAudioFormat format;
    uint32_t frame_count;
    RVReadStatus status;
} RVReadInfo;

typedef struct RVReadData {
    void* channels_output;
    uint32_t channels_output_max_bytes_size;
    RVReadInfo info;
} RVReadData;

typedef struct RVVizStructure {
    uint32_t caps;
    RVScrollMode scroll_mode;
    uint32_t pattern_channel_count;
    uint32_t scope_channel_count;
    uint32_t column_count;
} RVVizStructure;

typedef struct RVColumnDesc {
    uint8_t label[16];
    uint8_t char_width;
    RVColumnKind kind;
} RVColumnDesc;

typedef struct RVChannelDesc {
    uint8_t name[24];
    uint8_t scope_width;
} RVChannelDesc;

typedef struct RVVizPosition {
    uint32_t order;
    uint32_t pattern;
    uint32_t row;
    uint32_t window_lo;
    uint32_t window_hi;
} RVVizPosition;

typedef struct RVCell {
    uint32_t raw;
    uint8_t text[16];
} RVCell;

typedef struct RVPlaybackPlugin {
    uint64_t api_version;
    const char* name;
    const char* version;
    const char* library_version;
    RVProbeResult (*probe_can_play)(uint8_t* data, uint64_t data_size, const char* filename, uint64_t total_size);
    const char* (*supported_extensions)(void);
    void* (*create)(const RVService* services);
    int32_t (*destroy)(void* user_data);
    void (*event)(void* user_data, uint8_t* data, uint64_t data_size);
    int32_t (*open)(void* user_data, const char* url, uint32_t subsong, const RVService* services);
    void (*close)(void* user_data);
    RVReadInfo (*read_data)(void* user_data, RVReadData dest);
    int64_t (*seek)(void* user_data, int64_t ms);
    int32_t (*metadata)(const char* url, const RVService* services);
    void (*static_init)(const RVService* services);
    RVSettingsUpdate (*settings_updated)(void* user_data, const RVService* services);
    void (*static_destroy)(void);
    bool (*get_structure)(void* user_data, RVVizStructure* out);
    uint32_t (*get_columns)(void* user_data, RVColumnDesc* out, uint32_t cap);
    uint32_t (*get_pattern_channels)(void* user_data, RVChannelDesc* out, uint32_t cap);
    uint32_t (*get_scope_channels)(void* user_data, RVChannelDesc* out, uint32_t cap);
    bool (*get_position)(void* user_data, RVVizPosition* out);
    uint32_t (*get_channel_rows)(void* user_data, uint32_t* out, uint32_t cap);
    uint32_t (*get_cells)(void* user_data, int32_t channel, uint32_t row_lo, uint32_t row_hi, RVCell* out, uint32_t cap);
    void (*set_scope_enabled)(void* user_data, bool on);
    uint32_t (*get_scope_samples)(void* user_data, int32_t channel, float* out, uint32_t cap);
    uint32_t (*get_vu)(void* user_data, float* out, uint32_t cap);
} RVPlaybackPlugin;


#ifdef __cplusplus
}
#endif
