// @generated by api_gen — DO NOT EDIT. Regenerate with scripts/gen_bindings.sh.

#pragma once

#include <stdint.h>
#include "audio_format.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum RVResampleSettingsUpdate {
    RVResampleSettingsUpdate_Default = 0,
    RVResampleSettingsUpdate_RequireRestart = 1,
} RVResampleSettingsUpdate;

typedef struct RVService RVService;

typedef struct RVSettings RVSettings;

typedef struct RVConvertConfig {
    RVAudioFormat input;
    RVAudioFormat output;
} RVConvertConfig;

typedef struct RVResamplePlugin {
    uint64_t api_version;
    const char* name;
    const char* version;
    const char* library_version;
    void* (*create)(const RVService* services);
    int32_t (*destroy)(void* user_data);
    void (*set_config)(void* user_data, const RVConvertConfig* format);
    uint32_t (*convert)(void* user_data, void* output_data, void* input_data, uint32_t input_frame_count);
    uint32_t (*get_expected_output_frame_count)(void* user_data, uint32_t frame_count);
    uint32_t (*get_required_input_frame_count)(void* user_data, uint32_t frame_count);
    void (*static_init)(const RVService* services);
    RVResampleSettingsUpdate (*settings_updated)(void* user_data, const RVSettings* settings);
} RVResamplePlugin;


#ifdef __cplusplus
}
#endif
